// <auto-generated />
namespace UNIVERSE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class makeNameNotnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makeNameNotnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201908161402306_makeNameNotnullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
